CREATE TABLE IF NOT EXISTS blog_posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    movie_title VARCHAR(255),
    release_date DATE,
    director VARCHAR(100),
    genre VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS users(
    id INT AUTO_INCREMENT PRIMARY KEY,
    user VARCHAR(255) NOT NULL, 
    password VARCHAR(255) NOT NULL
)